regions:
  port:
    region: port                                #region that can be captured
    name: Port                                  #region in-game alias
    time_to_capture: 10                         #time required to capture the region
    time_to_keep: 20                            #time to keep region captured and to release it afterwards in
                                                #case it was not visited by owner during time_to_keep time
    min_clan_players: 1                         #minimum clan players avaliable in the region to start capturing
    perm_to_set: clansbattle.captured           #permission that is given to every member of the clan that owns the region
    owner_player_payout: 200                    #per player payout
    allies_player_payout: 150                   #allies clan members payout
    clan_payout_as_owner: 100                   #clan-owner payout
    clan_payout_as_ally: 50                     #clan-ally payout
    clan_payout_as_ally_to_owner: 50            #part of ally clan payout that it pays to owner clan
    period: 60                                  #payout period
    msg_prefix: "§6[§9Clans Batlle§6]§f"
    owner_suffix: "§6[§4AGGRESSOR§4]§f"
    ally_suffix: "§6[§dСОЮЗНИК§4]§f"
