name: CompareItems
description: "Plugin allows clans to battle for regions."
version: 1.0
main: net.dinikin.compareitems.plugin.CompareItemsPlugin
depend: [ShopGUIPlus]
commands:
  cmpi:
    description: Compare Items V1.0
  compareitems:
    description: Compare Items V1.0
